# Name of workflow
name: unittest_output

on:
  push:
    branches:
      - 'main'
    paths:
      - 'models/**.pkl'
  workflow_dispatch:
    branches:
    - 'main'

  # Github does not allow automatic workflow triggering from other workflows to avoid recursive workflow triggering.
  # To ensure that our unittest_output also runs when new outputs are pushed from the pipeline workflow, we need to add the code below.
  workflow_run:
    workflows: ["run-pipeline"]
    types:
      - completed
      
jobs:
  output_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: create_output_data
        run: |
          pip install pandas
          pip install scikit-learn
          python inference.py
      
      - name: output_test
        uses: ./.github/actions/unittest_output
        
