# Name of workflow
name: unittest_output

on:
  push:
    branches:
      - 'main'
    paths:
      - 'models/trained_model.pkl'
  workflow_dispatch:
    branches:
    - 'main'
      
jobs:
  output_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: create_output_data
        run: |
          pip install pandas
          pip install pickle
          python inference.py
      
      - name: output_test
        uses: ./.github/actions/unittest_output
        
